// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Component, OnInit, Renderer2 } from '@angular/core';
import { Router, ActivatedRoute } from "@angular/router";
import { HttpEventType } from '@angular/common/http';

import { AutorModel } from 'src/app/models/autor.model';
import { AutorService } from 'src/app/services/autor.service';
import { SToastService } from 'src/app/components/shared/s-toast/s-toast.service';
import { SModalLoadingService } from 'src/app/components/shared/s-modal-loading/s-modal-loading.service';
import { UploadFileModel } from 'src/app/models/upload_file.model';
import { environment } from 'src/environments/environment';


@Component({
  selector: 'app-d-edit-autor',
  standalone: false,

  templateUrl: './d-edit-autor.component.html'
})
export class DEditAutorComponent implements OnInit {
  mAutor: AutorModel = new AutorModel();

  mIdx = ""

  mFileURL = environment.file.endpoint;
  mImageUrl: string = "";
  uploadProgress: number = 0;

  disabled = false;

  constructor(public mRenderer: Renderer2, private mRouter: Router, private mActivatedRoute: ActivatedRoute, private mAutorService: AutorService,
    private mSToastService: SToastService, private mSModalLoadingService: SModalLoadingService) {

    let mEventClose = this.mSModalLoadingService.show();
    this.mActivatedRoute.params.subscribe(params => {

      this.mIdx = params['idx'];

      this.mAutorService.get(this.mIdx).subscribe({
        error: (err: any) => {

          switch (err.error['code']) {
            case '20':
              this.mSToastService.danger(`Ya existe un registro parecido a este... No se pueden repetir los campos clave`);
              break;
            default:
              this.mSToastService.danger(`Error inesperado, intenta mas tarde (Code: 01)`);
              break;
          }
        },
        next: (result: any) => {


          // result
          this.mAutor = result.autor;

          // let timeStamp = (new Date()).getTime();
          // this.mImageUrl = `${this.mFileURL}${this.mAutor.autor_url_logo}?t=${timeStamp}`;
        }

      }).add(() => {
        mEventClose.next();
      });

    });
  }

  ngOnInit(): void {
  }

  uploadFile(mUploadFileModel: UploadFileModel) {
    this.mAutorService.fileUpload(mUploadFileModel.field, mUploadFileModel.file, this.mAutor.idx).subscribe(event => {

      if (event.type === HttpEventType.UploadProgress) {

        const percent = Math.round(event.loaded * 100 / event.total);
        if ((percent - this.uploadProgress) > 8 || percent === 100) {
          this.uploadProgress = percent;
        }
      }

      if (event.type === HttpEventType.Response) {


        setTimeout(() => {
          this.uploadProgress = 0;
          this.mRouter.navigateByUrl('/', { skipLocationChange: true }).then(() => {
            this.mRouter.navigate(['/autors', 'edit', this.mIdx]);
          });
        }, 500);
      }
    })
  }

  deleteFile(mField: string) {

    // IMPORTANTE: en el segundo parametro se puede enviar el campo que contiene imagen, para eliminar en caso de borrar registro, ej: this.mAutor.autor_url_image

    let mEventClose = this.mSModalLoadingService.show();
    this.mAutorService.fileRemove(mField, this.mAutor.idx, null).subscribe({
      error: (err: any) => {

        switch (err.error['code']) {
          default:
            this.mSToastService.danger(`Error inesperado, intenta mas tarde (Code: 01)`);
            break;
        }
      },
      next: (result: any) => {


        // result
        setTimeout(() => {
          this.uploadProgress = 0;
          this.mRouter.navigateByUrl('/', { skipLocationChange: true }).then(() => {
            this.mRouter.navigate(['/autors', 'edit', this.mIdx]);
          });
        }, 500);
      }

    }).add(() => {
      mEventClose.next();
    });
  }

  save(mAutor: AutorModel) {
    this.mAutor = mAutor;

    let mEventClose = this.mSModalLoadingService.show();
    this.mAutorService.update(this.mAutor, this.mIdx).subscribe({
      error: (err: any) => {

        switch (err.error['code']) {
          case '20':
            this.mSToastService.danger(`Ya existe un registro parecido a este... No se pueden repetir los campos clave`);
            break;
          default:
            this.mSToastService.danger(`Error inesperado, intenta mas tarde (Code: 01)`);
            break;
        }
      },
      next: (result: any) => {


        // result
        this.mRouter.navigate(['/autors']);
      }

    }).add(() => {
      mEventClose.next();
    });
  }
}
