// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Params, Router, RouterLink } from "@angular/router";
import { take } from 'rxjs/operators';
import * as XLSX from 'xlsx';
import { PageHeaderComponent } from '../../../../layout/page-header/page-header.component';

import { SongService } from 'src/app/services/song.service';
import { SToastService } from 'src/app/components/shared/s-toast/s-toast.service';
import { SModalLoadingService } from 'src/app/components/shared/s-modal-loading/s-modal-loading.service';
import { SongModel } from 'src/app/models/song.model';
import { OrderModel } from 'src/app/models/order.model';
import { SModalYesNoService } from 'src/app/components/shared/s-modal-yes-no/s-modal-yes-no.service';
import { DSearchSongComponent } from '../d-search-song/d-search-song.component';
import { LucideAngularModule } from 'lucide-angular';


@Component({
    selector: 'app-d-list-song',
    templateUrl: './d-list-song.component.html',
    imports: [PageHeaderComponent, RouterLink, DSearchSongComponent, LucideAngularModule],
})
export class DListSongComponent implements OnInit {

  mSong: SongModel = new SongModel();
  mOrder: OrderModel = new OrderModel();
  mSongs: any = [];

  mPages: any = [];
  mPage: number = 0;
  mTotalPages: number = 0;

  mFromRegisters: number = 0;
  mToRegisters: number = 0;
  mRegisters: number = 0;
  mTotalRegisters: number = 0;

  constructor(private mRouter: Router, private mSongService: SongService, private mSToastService: SToastService,
    private mSModalLoadingService: SModalLoadingService, private mSModalYesNoService: SModalYesNoService,
    private mActivatedRoute: ActivatedRoute) {

    // Read URL query state once on entry, then fetch. Subscribing once with
    // take(1) avoids a loop where setUrlQuery() re-triggers this callback.
    this.mActivatedRoute.queryParams.pipe(take(1)).subscribe(params => {
      try {
        if (params['model']) this.mSong = JSON.parse(decodeURIComponent(params['model']));
        if (params['order']) this.mOrder = JSON.parse(decodeURIComponent(params['order']));
        if (params['page'] != null) this.mPage = Number(params['page']) || 0;
      } catch { /* ignore malformed URL params; fall back to defaults */ }
      this.getAll();
    });
  }

  ngOnInit(): void {
  }

  search(mModel: { mSong: SongModel, mOrder: OrderModel }) {
    this.mSong = mModel.mSong;
    this.mOrder = mModel.mOrder;
    this.mPage = 0;
    this.setUrlQuery();
  }

  setUrlQuery() {
    const queryParams: Params = { model: encodeURIComponent(JSON.stringify(this.mSong)), order: encodeURIComponent(JSON.stringify(this.mOrder)), page: Number(this.mPage) }

    this.mRouter.navigate([],
      {
        relativeTo: this.mActivatedRoute,
        queryParams,
        queryParamsHandling: 'merge', // remove to replace all query params by provided
      });

    this.getAll();
  }

  getAll() {


    let mEventClose = this.mSModalLoadingService.show();
    this.mSongService.all(this.mSong, this.mOrder, this.mPage).subscribe({
      error: (err: any) => {

        switch (err.error['code']) {
          default:
            this.mSToastService.danger(`Error inesperado, intenta mas tarde (Code: 01)`);
            break;
        }
      },
      next: (result: any) => {


        // result
        this.mPages = [];
        this.mTotalPages = result.pages;
        for (let i = 0; i < this.mTotalPages; i++) {
          this.mPages.push({ idx: i, name: `Página ${i + 1} de ${this.mTotalPages}` });
        }

        this.mFromRegisters = result.from;
        this.mToRegisters = result.to;
        this.mRegisters = result.size;
        this.mTotalRegisters = result.total;
        this.mSongs = result.songs;
      }

    }).add(() => {
      mEventClose.next();
    });
  }

  changePage(mPage) {

    this.mPage = mPage;
    this.getAll();
  }

  show(mIdx: string) {
    this.mRouter.navigate(['/songs/show', mIdx]);
  }

  edit(mIdx: string) {
    this.mRouter.navigate(['/songs/edit', mIdx]);
  }

  delete(mIdx: string, mName: string, mKeyField: string) {


    let responseEvent = this.mSModalYesNoService.danger(`¿Confirma eliminar Cancion \"${mName}\"?`, "¿Eliminar Cancion?");
    responseEvent.subscribe((response) => {
      this.confirmDelete(mIdx, response, mKeyField);
    });
  }

  confirmDelete(mIdx: string, mResult: boolean, mKeyField: string) {
    if (mResult) {

      let mEventClose = this.mSModalLoadingService.show();
      this.mSongService.remove(mIdx /*, mKeyField */).subscribe({
        error: (err: any) => {

          switch (err.error['code']) {
            case '55':
              this.mSToastService.danger(`No se puede eliminar... este registro se usa en otro lugar`);
              break;
            default:
              this.mSToastService.danger(`Error inesperado, intenta mas tarde (Code: 01)`);
              break;
          }
        },
        next: (result: any) => {


          // result
          this.mPage = 0;
          this.getAll();
        }

      }).add(() => {
        mEventClose.next();
      });
    }
  }

  exportToExcel() {
    let fileName = 'songs';

    let targetTableElm = document.querySelectorAll("table.table")[0];
    let wb = XLSX.utils.table_to_book(targetTableElm, <XLSX.Table2SheetOpts>{
      sheet: 'Hoja 1',
    });
    XLSX.writeFile(wb, `${fileName}.xlsx`);
  }
}
