// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Component, OnInit, Renderer2 } from '@angular/core';
import { Router, ActivatedRoute } from "@angular/router";
import { SongService } from 'src/app/services/song.service';
import { SToastService } from '../../../shared/s-toast/s-toast.service';
import { SModalLoadingService } from '../../../shared/s-modal-loading/s-modal-loading.service';
import { environment } from 'src/environments/environment';
import { SongModel } from '../../../../models/song.model';

@Component({
  selector: 'app-d-show-song',
  standalone: false,

  templateUrl: './d-show-song.component.html'
})
export class DShowSongComponent implements OnInit {

  mSong: any = {};
  mAutor: any = {};

  mIdx = ""

  mFileURL = environment.file.endpoint;
  mImageUrl: string = "";

  constructor(public mRenderer: Renderer2, private mRouter: Router, private mActivatedRoute: ActivatedRoute, private mSongService: SongService,
    private mSToastService: SToastService, private mSModalLoadingService: SModalLoadingService) {

    let mEventClose = this.mSModalLoadingService.show();
    this.mActivatedRoute.params.subscribe(params => {

      this.mIdx = params['idx'];

      this.mSongService.get(this.mIdx).subscribe({
        error: (err: any) => {

          switch (err.error['code']) {
            default:
              this.mSToastService.danger(`Error inesperado, intenta mas tarde (Code: 01)`);
              break;
          }
        },
        next: (result: any) => {


          // result
          this.mSong = result.song;
          this.mAutor = result.song.autor;
          // let timeStamp = (new Date()).getTime();
          // this.mImageUrl = `${this.mFileURL}${this.mSong.song_url_logo}?t=${timeStamp}`;

        },
      }).add(() => {
        mEventClose.next();
      });

    });
  }

  ngOnInit(): void {
  }

}
