// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Component, OnInit, Input, Output, EventEmitter, ElementRef, ViewChild, Renderer2, SimpleChanges, OnChanges } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';

import { SToastService } from 'src/app/components/shared/s-toast/s-toast.service';
import { SModalLoadingService } from 'src/app/components/shared/s-modal-loading/s-modal-loading.service';
import { AutorModel } from 'src/app/models/autor.model';

import { SModalOptionService } from 'src/app/components/shared/s-modal-option/s-modal-option.service';


@Component({
  selector: 'app-d-form-autor',
  standalone: false,

  templateUrl: './d-form-autor.component.html'
})
export class DFormAutorComponent implements OnInit, OnChanges {

  @Input() mAutor: AutorModel = new AutorModel()
  @Output() mAutorResponse: EventEmitter<AutorModel>;
  mForm: FormGroup;

  mValidators = Validators;


  mOptionText = {};


  constructor(public mRenderer: Renderer2, private mFormBuilder: FormBuilder, private mSToastService: SToastService, private mSModalLoadingService: SModalLoadingService,
    private mSModalOptionService: SModalOptionService,) {

    this.mAutorResponse = new EventEmitter();
    this.buildForm()



  }

  ngOnInit(): void {
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['mAutor'] && changes['mAutor'].currentValue) {

    }
  }

  showModalOption(mTitle: string, mOptions: any[], mField: string, mNull: boolean = false) {
    if (mNull) {
      this.mAutor[mField] = null;
      this.mForm.get(mField)?.setValue(null);
      this.mOptionText[mField] = null;
    } else {
      let mResponseEvent = this.mSModalOptionService.show(mTitle, mOptions, mField);
      mResponseEvent.subscribe((response) => {
        if (response !== null) {
          this.mAutor[mField] = response;
          this.mOptionText[mField] = mOptions.find(opt => opt.idx == response)?.name;
        }
      });
    }
  }

  buildForm() {
    this.mForm = this.mFormBuilder.group({
      autor_name: ['', [Validators.required, Validators.minLength(1), Validators.maxLength(255), Validators.pattern(/^[A-Za-zÁÉÍÓÚáéíóúñÑ0-9\s]+[^\'\"]*$/)]],

    })
  }

  get mAutorNameValid() { return this.mForm.get('autor_name').invalid && this.mForm.get('autor_name').touched }


  save() {

    if (this.mForm.invalid) {
      this.mSToastService.danger("Corrige los errores del formulario para continuar");
      return Object.values(this.mForm.controls).forEach(control => {
        control.markAsTouched()
      })
    }

    this.mAutorResponse.emit(this.mAutor);
  }

}


