// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Component, OnInit, Input, Output, EventEmitter, ElementRef, ViewChild, Renderer2, SimpleChanges, OnChanges } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';

import { SToastService } from 'src/app/components/shared/s-toast/s-toast.service';
import { SModalLoadingService } from 'src/app/components/shared/s-modal-loading/s-modal-loading.service';
import { SongModel } from 'src/app/models/song.model';
import { OrderModel } from 'src/app/models/order.model';

import { SModalOptionService } from 'src/app/components/shared/s-modal-option/s-modal-option.service';

import { AutorService } from 'src/app/services/autor.service';


@Component({
  selector: 'app-d-search-song',
  standalone: false,

  templateUrl: './d-search-song.component.html'
})
export class DSearchSongComponent implements OnInit, OnChanges {

  @Input() mSong: SongModel = new SongModel()
  @Input() mOrder: OrderModel = new OrderModel()
  @Output() mSongResponse: EventEmitter<{ mSong: SongModel, mOrder: OrderModel }>;
  mForm: FormGroup;

  mValidators = Validators;

  mOptionsAutorIdx = [];

  mOptionText = { "autor_idx": "" };


  mOptionOrderField = [{ "idx": "song_name", "name": "Nombre" }, { "idx": "autor_idx", "name": "Autor" }, { "idx": "song_year", "name": "Año" }, { "idx": "song_content", "name": "Contenido" }, { "idx": "createdAt", "name": "Creación" }, { "idx": "updatedAt", "name": "Actualización" }]
  mOptionOrderDirection = [{ idx: 'DESC', name: 'Descendete' }, { idx: 'ASC', name: 'Ascendente' }];
  mOptionOrderCount = [{ idx: 10, name: '10' }, { idx: 30, name: '30' }, { idx: 50, name: '50' }, { idx: 100, name: '100' }];

  mOptionOrderText = {
    order_field: '',
    order_direction: '',
    order_count: ''
  }

  constructor(public mRenderer: Renderer2, private mFormBuilder: FormBuilder, private mSToastService: SToastService,
    private mSModalLoadingService: SModalLoadingService, private mSModalOptionService: SModalOptionService,
    private mActivatedRoute: ActivatedRoute, private mAutorService: AutorService,) {

    this.mSongResponse = new EventEmitter();
    this.buildForm();
    this.clear();

    // get AutorIdx 
    // ----------------------------------------------------------------------------- 
    let mEventLoadingAutor = this.mSModalLoadingService.show();
    this.mAutorService.selection().subscribe((result: any) => {
      if (result['code'] != '00') {
        this.mSToastService.danger("Error inesperado");
      } else if (result['code'] == '00') {
        this.mOptionsAutorIdx = result.autors;
      }
    }).add(() => {
      mEventLoadingAutor.next();
    });



    this.mActivatedRoute.queryParams.subscribe(params => {
      if (Object.keys(params).length > 0) {
        this.mSong = JSON.parse(decodeURIComponent(params['model']));
        this.mOrder = JSON.parse(decodeURIComponent(params['order']));
      }
    });

  }

  ngOnInit(): void {
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['mSong'] && changes['mSong'].currentValue) {
      this.mOptionText['autor_idx'] = this.mSong.autor_idx == null ? '' : this.mOptionsAutorIdx.find(opt => opt.idx.toString() == this.mSong.autor_idx)?.name || '';

    }

    if (changes['mOrder'] && changes['mOrder'].currentValue) {
      this.mOptionOrderText['order_field'] = this.mOrder.order_field == null ? '' : this.mOptionOrderField.find(opt => opt.idx.toString() == this.mOrder.order_field)?.name || '';
      this.mOptionOrderText['order_direction'] = this.mOrder.order_direction == null ? '' : this.mOptionOrderDirection.find(opt => opt.idx.toString() == this.mOrder.order_direction)?.name || '';
      this.mOptionOrderText['order_count'] = this.mOrder.order_count == null ? '' : this.mOptionOrderCount.find(opt => opt.idx == this.mOrder.order_count)?.name || '';
    }
  }

  showModalOption(mTitle: string, mOptions: any[], mField: string, mNull: boolean = false) {
    if (mNull) {
      this.mSong[mField] = null;
      this.mForm.get(mField)?.setValue(null);
      this.mOptionText[mField] = null;
    } else {
      let mResponseEvent = this.mSModalOptionService.show(mTitle, mOptions, mField);
      mResponseEvent.subscribe((response) => {
        if (response !== null) {
          this.mSong[mField] = response;
          this.mOptionText[mField] = mOptions.find(opt => opt.idx == response)?.name;
        }
      });
    }
  }

  showModalOptionOrder(mTitle: string, mOptions: any[], mField: string, mNull: boolean = false) {
    if (mNull) {
      this.mOrder[mField] = null;
      this.mForm.get(mField)?.setValue(null);
      this.mOptionOrderText[mField] = null;
    } else {
      let mResponseEvent = this.mSModalOptionService.show(mTitle, mOptions, mField);
      mResponseEvent.subscribe((response) => {
        if (response !== null) {
          this.mOrder[mField] = response;
          this.mOptionOrderText[mField] = mOptions.find(opt => opt.idx == response)?.name;
        }
      });
    }
  }

  buildForm() {
    this.mForm = this.mFormBuilder.group({
      song_name: ['', [Validators.maxLength(255), Validators.pattern(/^[A-Za-zÁÉÍÓÚáéíóúñÑ0-9\s]+[^\'\"]*$/)]],
      autor_idx: ['', [Validators.maxLength(255), Validators.pattern(/^[A-Za-zÁÉÍÓÚáéíóúñÑ0-9\s]+[^\'\"]*$/)]],
      song_year: ['', [Validators.maxLength(255), Validators.pattern(/^[A-Za-zÁÉÍÓÚáéíóúñÑ0-9\s]+[^\'\"]*$/)]],
      song_content: ['', [Validators.maxLength(255), Validators.pattern(/^[A-Za-zÁÉÍÓÚáéíóúñÑ0-9\s]+[^\'\"]*$/)]],

      order_field: ['', [Validators.maxLength(255)]],
      order_direction: ['', [Validators.maxLength(255)]],
      order_count: ['', [Validators.maxLength(255)]],
    })
  }

  get mSongNameValid() { return this.mForm.get('song_name').invalid && this.mForm.get('song_name').touched }
  get mAutorIdxValid() { return this.mForm.get('autor_idx').invalid && this.mForm.get('autor_idx').touched }
  get mSongYearValid() { return this.mForm.get('song_year').invalid && this.mForm.get('song_year').touched }
  get mSongContentValid() { return this.mForm.get('song_content').invalid && this.mForm.get('song_content').touched }

  get mOrderFieldValid() { return this.mForm.get('order_field').invalid && this.mForm.get('order_field').touched }
  get mOrderDirectionValid() { return this.mForm.get('order_direction').invalid && this.mForm.get('order_direction').touched }
  get mOrderCountValid() { return this.mForm.get('order_count').invalid && this.mForm.get('order_count').touched }

  clear() {
    this.mSong.song_name = null
    this.mSong.autor_idx = null
    this.mSong.song_year = null
    this.mSong.song_content = null


    this.mOrder.order_field = 'createdAt';
    this.mOrder.order_direction = 'DESC';
    this.mOrder.order_count = 30;

    this.mOptionOrderText['order_field'] = this.mOrder.order_field == null ? '' : this.mOptionOrderField.find(opt => opt.idx.toString() == this.mOrder.order_field)?.name || '';
    this.mOptionOrderText['order_direction'] = this.mOrder.order_direction == null ? '' : this.mOptionOrderDirection.find(opt => opt.idx.toString() == this.mOrder.order_direction)?.name || '';
    this.mOptionOrderText['order_count'] = this.mOrder.order_count == null ? '' : this.mOptionOrderCount.find(opt => opt.idx == this.mOrder.order_count)?.name || '';

    this.mSongResponse.emit({ mSong: this.mSong, mOrder: this.mOrder });
  }

  search() {

    if (this.mForm.invalid) {
      this.mSToastService.danger("Corrige los errores del formulario para continuar");
      return Object.values(this.mForm.controls).forEach(control => {
        control.markAsTouched()
      })
    }

    this.mSongResponse.emit({ mSong: this.mSong, mOrder: this.mOrder });
  }

}


