// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Component, OnInit, Input, Output, EventEmitter, ElementRef, ViewChild, SimpleChanges, OnChanges } from '@angular/core';
import { FormGroup, FormBuilder, Validators, ReactiveFormsModule } from '@angular/forms';

import { SToastService } from 'src/app/components/shared/s-toast/s-toast.service';
import { SModalLoadingService } from 'src/app/components/shared/s-modal-loading/s-modal-loading.service';
import { SongModel } from 'src/app/models/song.model';

import { SModalOptionService } from 'src/app/components/shared/s-modal-option/s-modal-option.service';
import { AutorService } from 'src/app/services/autor.service';
import { BackButtonDirective } from '../../../../directives/back-button.directive';
import { LucideAngularModule } from 'lucide-angular';


@Component({
    selector: 'app-d-form-song',
    templateUrl: './d-form-song.component.html',
    imports: [ReactiveFormsModule, BackButtonDirective, LucideAngularModule]
})
export class DFormSongComponent implements OnInit, OnChanges {

  @Input() mSong: SongModel = new SongModel()
  @Output() mSongResponse: EventEmitter<SongModel>;
  mForm: FormGroup;

  mValidators = Validators;

  mOptionsAutorIdx = [];

  mOptionText = { "autor_idx": "" };


  constructor(private mFormBuilder: FormBuilder, private mSToastService: SToastService, private mSModalLoadingService: SModalLoadingService,
    private mSModalOptionService: SModalOptionService, private mAutorService: AutorService,) {

    this.mSongResponse = new EventEmitter();
    this.buildForm()
  }

  ngOnInit(): void {
    // get AutorIdx 
    // ----------------------------------------------------------------------------- 
    let mEventLoadingAutor = this.mSModalLoadingService.show();
    this.mAutorService.selection().subscribe((result: any) => {
      if (result['code'] != '00') {
        this.mSToastService.danger("Error inesperado");
      } else if (result['code'] == '00') {
        this.mOptionsAutorIdx = result.autors;
        this.ngOnChanges({});
      }
    }).add(() => {
      mEventLoadingAutor.next();
    });
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['mSong'] && this.mForm) {
      this.mForm.patchValue({
        song_name: this.mSong?.song_name ?? '',
        song_year: this.mSong?.song_year ?? '',
        song_content: this.mSong?.song_content ?? '',
      }, { emitEvent: false });
    }
    // Once both mSong and the autors list are loaded, project the autor
    // UUID stored on mSong into the visible autor name in the form.
    if (this.mSong && this.mOptionsAutorIdx.length > 0) {
      const mSelectedAutor = this.mOptionsAutorIdx.find(opt => opt.idx?.toString() === this.mSong.autor_idx?.toString());
      const name = mSelectedAutor ? mSelectedAutor.name : '';
      this.mOptionText['autor_idx'] = name;
      this.mForm?.get('autor_idx')?.setValue(name, { emitEvent: false });
    }
  }

  showModalOption(mTitle: string, mOptions: any[], mField: string, mNull: boolean = false) {
    if (mNull) {
      this.mSong[mField] = null;
      this.mForm.get(mField)?.setValue('');
      this.mOptionText[mField] = '';
    } else {
      let mResponseEvent = this.mSModalOptionService.show(mTitle, mOptions, mField);
      mResponseEvent.subscribe((response) => {
        if (response !== null) {
          this.mSong[mField] = response;
          const name = mOptions.find(opt => opt.idx == response)?.name ?? '';
          this.mOptionText[mField] = name;
          this.mForm.get(mField)?.setValue(name);
        }
      });
    }
  }

  buildForm() {
    this.mForm = this.mFormBuilder.group({
      song_name: ['', [Validators.required, Validators.minLength(1), Validators.maxLength(255), Validators.pattern(/^[A-Za-zÁÉÍÓÚáéíóúñÑ0-9\s]+[^\'\"]*$/)]],
      autor_idx: ['', [Validators.required, Validators.minLength(1), Validators.maxLength(255), Validators.pattern(/^[A-Za-zÁÉÍÓÚáéíóúñÑ0-9\s]+[^\'\"]*$/)]],
      song_year: ['', [Validators.minLength(1), Validators.maxLength(255), Validators.pattern(/^[A-Za-zÁÉÍÓÚáéíóúñÑ0-9\s]+[^\'\"]*$/)]],
      song_content: ['', [Validators.required, Validators.minLength(1), Validators.maxLength(5000)]],

    })
  }

  get mSongNameValid() { return this.mForm.get('song_name').invalid && this.mForm.get('song_name').touched }
  get mAutorIdxValid() { return this.mForm.get('autor_idx').invalid && this.mForm.get('autor_idx').touched }
  get mSongYearValid() { return this.mForm.get('song_year').invalid && this.mForm.get('song_year').touched }
  get mSongContentValid() { return this.mForm.get('song_content').invalid && this.mForm.get('song_content').touched }


  save() {

    if (this.mForm.invalid) {
      this.mSToastService.danger("Corrige los errores del formulario para continuar");
      return Object.values(this.mForm.controls).forEach(control => {
        control.markAsTouched()
      })
    }

    // Sync form values back into mSong; autor_idx already holds the UUID set
    // by showModalOption — the form just carries the visible name.
    const v = this.mForm.value;
    this.mSong.song_name = v.song_name;
    this.mSong.song_year = v.song_year;
    this.mSong.song_content = v.song_content;

    this.mSongResponse.emit(this.mSong);
  }

}


