// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Component, OnInit, Input, Output, EventEmitter, ElementRef, ViewChild, Renderer2, SimpleChanges, OnChanges } from '@angular/core';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';

import { SToastService } from 'src/app/components/shared/s-toast/s-toast.service';
import { SModalLoadingService } from 'src/app/components/shared/s-modal-loading/s-modal-loading.service';
import { SongModel } from 'src/app/models/song.model';

import { SModalOptionService } from 'src/app/components/shared/s-modal-option/s-modal-option.service';
import { AutorService } from 'src/app/services/autor.service';


@Component({
  selector: 'app-d-form-song',
  standalone: false,

  templateUrl: './d-form-song.component.html'
})
export class DFormSongComponent implements OnInit, OnChanges {

  @Input() mSong: SongModel = new SongModel()
  @Output() mSongResponse: EventEmitter<SongModel>;
  mForm: FormGroup;

  mValidators = Validators;

  mOptionsAutorIdx = [];

  mOptionText = { "autor_idx": "" };


  constructor(public mRenderer: Renderer2, private mFormBuilder: FormBuilder, private mSToastService: SToastService, private mSModalLoadingService: SModalLoadingService,
    private mSModalOptionService: SModalOptionService, private mAutorService: AutorService,) {

    this.mSongResponse = new EventEmitter();
    this.buildForm()
  }

  ngOnInit(): void {
    // get AutorIdx 
    // ----------------------------------------------------------------------------- 
    let mEventLoadingAutor = this.mSModalLoadingService.show();
    this.mAutorService.selection().subscribe((result: any) => {
      if (result['code'] != '00') {
        this.mSToastService.danger("Error inesperado");
      } else if (result['code'] == '00') {
        this.mOptionsAutorIdx = result.autors;
        this.ngOnChanges({});
      }
    }).add(() => {
      mEventLoadingAutor.next();
    });
  }

  ngOnChanges(changes: SimpleChanges) {
    if (this.mSong && this.mOptionsAutorIdx.length > 0) {
      const mSelectedAutor = this.mOptionsAutorIdx.find(opt => opt.idx.toString() === this.mSong.autor_idx?.toString());
      this.mOptionText['autor_idx'] = mSelectedAutor ? mSelectedAutor.name : '';
    }
  }

  showModalOption(mTitle: string, mOptions: any[], mField: string, mNull: boolean = false) {
    if (mNull) {
      this.mSong[mField] = null;
      this.mForm.get(mField)?.setValue(null);
      this.mOptionText[mField] = null;
    } else {
      let mResponseEvent = this.mSModalOptionService.show(mTitle, mOptions, mField);
      mResponseEvent.subscribe((response) => {
        if (response !== null) {
          this.mSong[mField] = response;
          this.mOptionText[mField] = mOptions.find(opt => opt.idx == response)?.name;
        }
      });
    }
  }

  buildForm() {
    this.mForm = this.mFormBuilder.group({
      song_name: ['', [Validators.required, Validators.minLength(1), Validators.maxLength(255), Validators.pattern(/^[A-Za-zÁÉÍÓÚáéíóúñÑ0-9\s]+[^\'\"]*$/)]],
      autor_idx: ['', [Validators.required, Validators.minLength(1), Validators.maxLength(255), Validators.pattern(/^[A-Za-zÁÉÍÓÚáéíóúñÑ0-9\s]+[^\'\"]*$/)]],
      song_year: ['', [Validators.minLength(1), Validators.maxLength(255), Validators.pattern(/^[A-Za-zÁÉÍÓÚáéíóúñÑ0-9\s]+[^\'\"]*$/)]],
      song_content: ['', [Validators.required, Validators.minLength(1), Validators.maxLength(5000)]],

    })
  }

  get mSongNameValid() { return this.mForm.get('song_name').invalid && this.mForm.get('song_name').touched }
  get mAutorIdxValid() { return this.mForm.get('autor_idx').invalid && this.mForm.get('autor_idx').touched }
  get mSongYearValid() { return this.mForm.get('song_year').invalid && this.mForm.get('song_year').touched }
  get mSongContentValid() { return this.mForm.get('song_content').invalid && this.mForm.get('song_content').touched }


  save() {

    if (this.mForm.invalid) {
      this.mSToastService.danger("Corrige los errores del formulario para continuar");
      return Object.values(this.mForm.controls).forEach(control => {
        control.markAsTouched()
      })
    }

    this.mSongResponse.emit(this.mSong);
  }

}


