// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Router } from '@angular/router';
import { Component, OnInit, Renderer2 } from '@angular/core';

import { SongModel } from 'src/app/models/song.model';
import { SongService } from 'src/app/services/song.service';
import { SToastService } from 'src/app/components/shared/s-toast/s-toast.service';
import { SModalLoadingService } from 'src/app/components/shared/s-modal-loading/s-modal-loading.service';


@Component({
  selector: 'app-d-new-song',
  standalone: false,

  templateUrl: './d-new-song.component.html'
})
export class DNewSongComponent implements OnInit {

  mSong: SongModel = new SongModel()

  constructor(public mRenderer: Renderer2, private mRouter: Router, private mSongService: SongService, private mSToastService: SToastService,
    private mSModalLoadingService: SModalLoadingService) {

  }

  ngOnInit(): void {
  }

  save(mSong: SongModel) {

    this.mSong = mSong;

    let mEventClose = this.mSModalLoadingService.show();
    this.mSongService.create(this.mSong).subscribe({
      error: (err: any) => {

        switch (err.error['code']) {
          case '20':
            this.mSToastService.danger(`Ya existe un registro parecido a este... No se pueden repetir los campos clave`);
            break;
          default:
            this.mSToastService.danger(`Error inesperado, intenta mas tarde (Code: 02)`);
            break;
        }
      },
      next: (result: any) => {

        switch (result['code']) {
          case '00':
            this.mRouter.navigate(['/songs']);

            break;
          default:
            this.mSToastService.danger(`Error inesperado, intenta mas tarde (Code: 01)`);
            break;
        }

      },


    }).add(() => {
      mEventClose.next();
    });
  }
}
