// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { throwError } from 'rxjs';
import { catchError, map } from "rxjs/operators";

import { AutorModel } from 'src/app/models/autor.model';
import { OrderModel } from 'src/app/models/order.model';
import { environment } from 'src/environments/environment';



@Injectable({
  providedIn: 'root'
})
export class AutorService {

  httpOptions = {
    headers: new HttpHeaders({
      'Content-Type': 'application/json'
    })
  };

  constructor(private http: HttpClient) { }

  // list
  all(mAutor: AutorModel, mOrder: OrderModel, mPage: number) {
    let body: any = {};
    body.autor = mAutor;
    body.order = mOrder;
    body.page = mPage;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/autors/all`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // select list
  selection() {
    let body: any = {};

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/autors/selection`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // get one
  get(mIdx: string) {
    let body: any = {};
    body.idx = mIdx;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/autors/get`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // new one
  create(mAutorModel: AutorModel) {
    let body: any = {};
    body.autor = mAutorModel;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/autors/create`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // edit one
  update(mAutorModel: AutorModel, mIdx: string) {
    let body: any = {};
    body.autor = mAutorModel;
    body.idx = mIdx;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/autors/update`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // remove one
  remove(mIdx: string) {
    let body: any = {};
    body.idx = mIdx;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/autors/remove`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }


}
