// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { throwError } from 'rxjs';
import { catchError, map } from "rxjs/operators";

import { BibleBibleModel } from 'src/app/models/bible_bible.model';
import { OrderModel } from 'src/app/models/order.model';
import { environment } from 'src/environments/environment';

@Injectable({
  providedIn: 'root'
})
export class BibleBibleService {

  httpOptions = {
    headers: new HttpHeaders({
      'Content-Type': 'application/json'
    })
  };

  constructor(private http: HttpClient) { }

  // select list
  selection() {
    let body: any = {};

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json'
    });

    return this.http.post(`${environment.apiUrl}/bible_bibles/selection`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // select list
  selectionBooks(mBibleIdx: string) {
    let body: any = {};
    body.bible_bible_idx = mBibleIdx;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json'
    });

    return this.http.post(`${environment.apiUrl}/bible_bibles/selection_books`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // select list
  selectionChapters(mBibleBibleIdx: string, mBibleBookIdx: string) {
    let body: any = {};
    body.bible_bible_idx = mBibleBibleIdx;
    body.bible_book_idx = mBibleBookIdx;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json'
    });

    return this.http.post(`${environment.apiUrl}/bible_bibles/selection_chapters`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // select list
  selectionVerses(mBibleBibleIdx: string, mBibleBookIdx: string, mBibleChapterIdx: string) {
    let body: any = {};
    body.bible_bible_idx = mBibleBibleIdx;
    body.bible_book_idx = mBibleBookIdx;
    body.bible_chapter_idx = mBibleChapterIdx;

    console.log(`==> ${mBibleBibleIdx} - ${mBibleBookIdx} - ${mBibleChapterIdx}`);

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json'
    });

    return this.http.post(`${environment.apiUrl}/bible_bibles/selection_verses`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

}
