// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { throwError } from 'rxjs';
import { catchError, map } from "rxjs/operators";

import { SongModel } from 'src/app/models/song.model';
import { OrderModel } from 'src/app/models/order.model';
import { environment } from 'src/environments/environment';



@Injectable({
  providedIn: 'root'
})
export class ServerService {

  httpOptions = {
    headers: new HttpHeaders({
      'Content-Type': 'application/json'
    })
  };

  constructor(private http: HttpClient) { }

  // get one
  get() {
    let body: any = {};

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/server/get`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }
}