// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { throwError } from 'rxjs';
import { catchError, map } from "rxjs/operators";

import { SongModel } from 'src/app/models/song.model';
import { OrderModel } from 'src/app/models/order.model';
import { environment } from 'src/environments/environment';



@Injectable({
  providedIn: 'root'
})
export class SongService {

  httpOptions = {
    headers: new HttpHeaders({
      'Content-Type': 'application/json'
    })
  };

  constructor(private http: HttpClient) { }

  // list
  all(mSong: SongModel, mOrder: OrderModel, mPage: number) {
    let body: any = {};
    body.song = mSong;
    body.order = mOrder;
    body.page = mPage;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json'
    });

    return this.http.post(`${environment.apiUrl}/songs/all`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // select list
  selection(mSong: SongModel, mOrder: OrderModel, mPage: number) {
    let body: any = {};
    body.song = mSong;
    body.order = mOrder;
    body.page = mPage;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/songs/selection`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // get one
  get(mIdx: string) {
    let body: any = {};
    body.idx = mIdx;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/songs/get`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // new one
  create(mSongModel: SongModel) {
    let body: any = {};
    body.song = mSongModel;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/songs/create`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // edit one
  update(mSongModel: SongModel, mIdx: string) {
    let body: any = {};
    body.song = mSongModel;
    body.idx = mIdx;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/songs/update`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // upload cover
  fileUpload(mField: string, mFileToUpload, mIdx: string) {
    let body = new FormData();
    body.append("field", mField);
    body.append("idx", mIdx);
    body.append("file", mFileToUpload);



    return this.http.post(`${environment.apiUrl}/songs/file/upload`, body, {
      reportProgress: true,
      observe: 'events',
      headers: new HttpHeaders({
        'field': mField,
        'idx': mIdx,
      })
    }).pipe(
      map(response => {
        if (response['code']) {
          if (response['code'] == '00') {

          }
        }

        return response
      }),
      catchError(err => {
        return throwError(() => err);
      })
    );
  }

  // delete cover
  fileRemove(mField: string, mIdx: string, mKey: string) {
    let body: any = {};
    body.field = mField;
    body.idx = mIdx;
    body.key = mKey;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/songs/file/remove`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }

  // remove one
  remove(mIdx: string) {
    let body: any = {};
    body.idx = mIdx;

    this.httpOptions.headers = new HttpHeaders({
      'Content-Type': 'application/json',

    });

    return this.http.post(`${environment.apiUrl}/songs/remove`, body, this.httpOptions)
      .pipe(
        map((response: Response) => {
          if (response['code']) {
            if (response['code'] == '00') {

            }
          }

          return response
        }),
        catchError(err => {
          return throwError(() => err);
        })
      );
  }


}
