// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Router } from '@angular/router';
import { Component, OnInit, Renderer2 } from '@angular/core';

import { AutorModel } from 'src/app/models/autor.model';
import { AutorService } from 'src/app/services/autor.service';
import { SToastService } from 'src/app/components/shared/s-toast/s-toast.service';
import { SModalLoadingService } from 'src/app/components/shared/s-modal-loading/s-modal-loading.service';


@Component({
  selector: 'app-d-new-autor',
  standalone: false,

  templateUrl: './d-new-autor.component.html'
})
export class DNewAutorComponent implements OnInit {

  mAutor: AutorModel = new AutorModel()

  constructor(public mRenderer: Renderer2, private mRouter: Router, private mAutorService: AutorService, private mSToastService: SToastService,
    private mSModalLoadingService: SModalLoadingService) {

  }

  ngOnInit(): void {
  }

  save(mAutor: AutorModel) {

    this.mAutor = mAutor;

    let mEventClose = this.mSModalLoadingService.show();
    this.mAutorService.create(this.mAutor).subscribe({
      error: (err: any) => {

        switch (err.error['code']) {
          case '20':
            this.mSToastService.danger(`Ya existe un registro parecido a este... No se pueden repetir los campos clave`);
            break;
          default:
            this.mSToastService.danger(`Error inesperado, intenta mas tarde (Code: 02)`);
            break;
        }
      },
      next: (result: any) => {

        switch (result['code']) {
          case '00':
            this.mRouter.navigate(['/autors']);

            break;
          default:
            this.mSToastService.danger(`Error inesperado, intenta mas tarde (Code: 01)`);
            break;
        }

      },


    }).add(() => {
      mEventClose.next();
    });
  }
}
