// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import { Component, OnInit, Input, Output, EventEmitter, ElementRef, ViewChild, Renderer2, SimpleChanges, OnChanges } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { FormGroup, FormBuilder, Validators } from '@angular/forms';

import { SToastService } from 'src/app/components/shared/s-toast/s-toast.service';
import { SModalLoadingService } from 'src/app/components/shared/s-modal-loading/s-modal-loading.service';
import { AutorModel } from 'src/app/models/autor.model';
import { OrderModel } from 'src/app/models/order.model';

import { SModalOptionService } from 'src/app/components/shared/s-modal-option/s-modal-option.service';



@Component({
  selector: 'app-d-search-autor',
  standalone: false,

  templateUrl: './d-search-autor.component.html'
})
export class DSearchAutorComponent implements OnInit, OnChanges {

  @Input() mAutor: AutorModel = new AutorModel()
  @Input() mOrder: OrderModel = new OrderModel()
  @Output() mAutorResponse: EventEmitter<{ mAutor: AutorModel, mOrder: OrderModel }>;
  mForm: FormGroup;

  mValidators = Validators;


  mOptionText = {};


  mOptionOrderField = [{ "idx": "autor_name", "name": "Nombre" }, { "idx": "createdAt", "name": "Creación" }, { "idx": "updatedAt", "name": "Actualización" }]
  mOptionOrderDirection = [{ idx: 'DESC', name: 'Descendete' }, { idx: 'ASC', name: 'Ascendente' }];
  mOptionOrderCount = [{ idx: 10, name: '10' }, { idx: 30, name: '30' }, { idx: 50, name: '50' }, { idx: 100, name: '100' }];

  mOptionOrderText = {
    order_field: '',
    order_direction: '',
    order_count: ''
  }

  constructor(public mRenderer: Renderer2, private mFormBuilder: FormBuilder, private mSToastService: SToastService,
    private mSModalLoadingService: SModalLoadingService, private mSModalOptionService: SModalOptionService,
    private mActivatedRoute: ActivatedRoute,) {

    this.mAutorResponse = new EventEmitter();
    this.buildForm();
    this.clear();



    this.mActivatedRoute.queryParams.subscribe(params => {
      if (Object.keys(params).length > 0) {
        this.mAutor = JSON.parse(decodeURIComponent(params['model']));
        this.mOrder = JSON.parse(decodeURIComponent(params['order']));
      }
    });

  }

  ngOnInit(): void {
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['mAutor'] && changes['mAutor'].currentValue) {

    }

    if (changes['mOrder'] && changes['mOrder'].currentValue) {
      this.mOptionOrderText['order_field'] = this.mOrder.order_field == null ? '' : this.mOptionOrderField.find(opt => opt.idx.toString() == this.mOrder.order_field)?.name || '';
      this.mOptionOrderText['order_direction'] = this.mOrder.order_direction == null ? '' : this.mOptionOrderDirection.find(opt => opt.idx.toString() == this.mOrder.order_direction)?.name || '';
      this.mOptionOrderText['order_count'] = this.mOrder.order_count == null ? '' : this.mOptionOrderCount.find(opt => opt.idx == this.mOrder.order_count)?.name || '';
    }
  }

  showModalOption(mTitle: string, mOptions: any[], mField: string, mNull: boolean = false) {
    if (mNull) {
      this.mAutor[mField] = null;
      this.mForm.get(mField)?.setValue(null);
      this.mOptionText[mField] = null;
    } else {
      let mResponseEvent = this.mSModalOptionService.show(mTitle, mOptions, mField);
      mResponseEvent.subscribe((response) => {
        if (response !== null) {
          this.mAutor[mField] = response;
          this.mOptionText[mField] = mOptions.find(opt => opt.idx == response)?.name;
        }
      });
    }
  }

  showModalOptionOrder(mTitle: string, mOptions: any[], mField: string, mNull: boolean = false) {
    if (mNull) {
      this.mOrder[mField] = null;
      this.mForm.get(mField)?.setValue(null);
      this.mOptionOrderText[mField] = null;
    } else {
      let mResponseEvent = this.mSModalOptionService.show(mTitle, mOptions, mField);
      mResponseEvent.subscribe((response) => {
        if (response !== null) {
          this.mOrder[mField] = response;
          this.mOptionOrderText[mField] = mOptions.find(opt => opt.idx == response)?.name;
        }
      });
    }
  }

  buildForm() {
    this.mForm = this.mFormBuilder.group({
      autor_name: ['', [Validators.maxLength(255), Validators.pattern(/^[A-Za-zÁÉÍÓÚáéíóúñÑ0-9\s]+[^\'\"]*$/)]],

      order_field: ['', [Validators.maxLength(255)]],
      order_direction: ['', [Validators.maxLength(255)]],
      order_count: ['', [Validators.maxLength(255)]],
    })
  }

  get mAutorNameValid() { return this.mForm.get('autor_name').invalid && this.mForm.get('autor_name').touched }

  get mOrderFieldValid() { return this.mForm.get('order_field').invalid && this.mForm.get('order_field').touched }
  get mOrderDirectionValid() { return this.mForm.get('order_direction').invalid && this.mForm.get('order_direction').touched }
  get mOrderCountValid() { return this.mForm.get('order_count').invalid && this.mForm.get('order_count').touched }

  clear() {
    this.mAutor.autor_name = null


    this.mOrder.order_field = 'createdAt';
    this.mOrder.order_direction = 'DESC';
    this.mOrder.order_count = 30;

    this.mOptionOrderText['order_field'] = this.mOrder.order_field == null ? '' : this.mOptionOrderField.find(opt => opt.idx.toString() == this.mOrder.order_field)?.name || '';
    this.mOptionOrderText['order_direction'] = this.mOrder.order_direction == null ? '' : this.mOptionOrderDirection.find(opt => opt.idx.toString() == this.mOrder.order_direction)?.name || '';
    this.mOptionOrderText['order_count'] = this.mOrder.order_count == null ? '' : this.mOptionOrderCount.find(opt => opt.idx == this.mOrder.order_count)?.name || '';

    this.mAutorResponse.emit({ mAutor: this.mAutor, mOrder: this.mOrder });
  }

  search() {

    if (this.mForm.invalid) {
      this.mSToastService.danger("Corrige los errores del formulario para continuar");
      return Object.values(this.mForm.controls).forEach(control => {
        control.markAsTouched()
      })
    }

    this.mAutorResponse.emit({ mAutor: this.mAutor, mOrder: this.mOrder });
  }

}


